"""add accommodation fields to students

Revision ID: 09be54edc469
Revises: c7e0388b5787
Create Date: 2026-07-28 22:08:15.082233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09be54edc469'
down_revision: Union[str, Sequence[str], None] = 'c7e0388b5787'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('accommodation_notes', sa.String(length=500), nullable=True))
    op.add_column('students', sa.Column('skip_face_check', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('students', sa.Column('skip_object_check', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('students', sa.Column('extra_time_minutes', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'extra_time_minutes')
    op.drop_column('students', 'skip_object_check')
    op.drop_column('students', 'skip_face_check')
    op.drop_column('students', 'accommodation_notes')
    # ### end Alembic commands ###
