"""add question-context snapshot fields to violations

Revision ID: 3dfb3eff3778
Revises: 79a6060cde08
Create Date: 2026-07-31 10:10:33.782761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dfb3eff3778'
down_revision: Union[str, Sequence[str], None] = '79a6060cde08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('violations', sa.Column('question_id', sa.Integer(), nullable=True))
    op.add_column('violations', sa.Column('question_text', sa.Text(), nullable=True))
    op.add_column('violations', sa.Column('question_type', sa.String(length=30), nullable=True))
    op.create_foreign_key(None, 'violations', 'questions', ['question_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'violations', type_='foreignkey')
    op.drop_column('violations', 'question_type')
    op.drop_column('violations', 'question_text')
    op.drop_column('violations', 'question_id')
    # ### end Alembic commands ###
