"""add max_risk_score to exams

Revision ID: 83c62cecbf5c
Revises: 8f51dd85ceeb
Create Date: 2026-08-06 15:54:25.224339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83c62cecbf5c'
down_revision: Union[str, Sequence[str], None] = '8f51dd85ceeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exams', sa.Column('max_risk_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exams', 'max_risk_score')
    # ### end Alembic commands ###
