"""add face_model_path to students

Revision ID: 8a17949fcf30
Revises: d6553d544afd
Create Date: 2026-07-23 11:11:52.379421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a17949fcf30'
down_revision: Union[str, Sequence[str], None] = 'd6553d544afd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('face_model_path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'face_model_path')
    # ### end Alembic commands ###
