"""add grading fields

Revision ID: 92d886002691
Revises: 51f44a175a3f
Create Date: 2026-07-18 11:10:21.619048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92d886002691'
down_revision: Union[str, Sequence[str], None] = '51f44a175a3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():

    op.add_column(
        "exam_sessions",
        sa.Column(
            "percentage",
            sa.Float(),
            nullable=False,
            server_default="0"
        )
    )

    op.add_column(
        "exam_sessions",
        sa.Column(
            "passed",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false")
        )
    )

    op.alter_column(
        "exam_sessions",
        "percentage",
        server_default=None
    )

    op.alter_column(
        "exam_sessions",
        "passed",
        server_default=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam_sessions', 'passed')
    op.drop_column('exam_sessions', 'percentage')
    # ### end Alembic commands ###
