"""add training review fields to violations

Revision ID: ad5cb6fe6bab
Revises: 88a97c5b9b35
Create Date: 2026-08-13 09:05:02.056881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad5cb6fe6bab'
down_revision: Union[str, Sequence[str], None] = '88a97c5b9b35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('violations', sa.Column('training_review_status', sa.String(length=20), nullable=True))
    op.add_column('violations', sa.Column('training_reviewed_by', sa.Integer(), nullable=True))
    op.add_column('violations', sa.Column('training_reviewed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('violations', sa.Column('training_exported_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'violations', 'users', ['training_reviewed_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'violations', type_='foreignkey')
    op.drop_column('violations', 'training_exported_at')
    op.drop_column('violations', 'training_reviewed_at')
    op.drop_column('violations', 'training_reviewed_by')
    op.drop_column('violations', 'training_review_status')
    # ### end Alembic commands ###
