"""add evidence and appeal fields to violations

Revision ID: c7e0388b5787
Revises: 83259d497eba
Create Date: 2026-07-28 16:02:02.792836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7e0388b5787'
down_revision: Union[str, Sequence[str], None] = '83259d497eba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('violations', sa.Column('evidence_path', sa.String(length=255), nullable=True))
    op.add_column('violations', sa.Column('appeal_reason', sa.String(length=1000), nullable=True))
    op.add_column('violations', sa.Column('appeal_status', sa.String(length=20), nullable=True))
    op.add_column('violations', sa.Column('appeal_response', sa.String(length=1000), nullable=True))
    op.add_column('violations', sa.Column('appeal_reviewed_by', sa.Integer(), nullable=True))
    op.add_column('violations', sa.Column('appeal_reviewed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'violations', 'users', ['appeal_reviewed_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'violations', type_='foreignkey')
    op.drop_column('violations', 'appeal_reviewed_at')
    op.drop_column('violations', 'appeal_reviewed_by')
    op.drop_column('violations', 'appeal_response')
    op.drop_column('violations', 'appeal_status')
    op.drop_column('violations', 'appeal_reason')
    op.drop_column('violations', 'evidence_path')
    # ### end Alembic commands ###
