"""add head_down_miss_streak to exam_sessions

Revision ID: d21ed63f6821
Revises: 3dfb3eff3778
Create Date: 2026-07-31 11:27:49.679077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd21ed63f6821'
down_revision: Union[str, Sequence[str], None] = '3dfb3eff3778'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_sessions', sa.Column('head_down_miss_streak', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam_sessions', 'head_down_miss_streak')
    # ### end Alembic commands ###
