"""add passing score

Revision ID: d52cceb5d009
Revises: 92d886002691
Create Date: 2026-07-18 11:21:39.980322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd52cceb5d009'
down_revision: Union[str, Sequence[str], None] = '92d886002691'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "exams",
        sa.Column(
            "passing_score",
            sa.Integer(),
            nullable=False,
            server_default="75"
        )
    )

    op.alter_column(
        "exams",
        "passing_score",
        server_default=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exams', 'passing_score')
    # ### end Alembic commands ###
