"""add first and last name to users

Revision ID: d617a2b1fc67
Revises: 95160a6d2756
Create Date: 2026-07-17 11:44:25.023057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd617a2b1fc67'
down_revision: Union[str, Sequence[str], None] = '95160a6d2756'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "first_name",
            sa.String(length=100),
            nullable=False,
            server_default=""
        )
    )

    op.add_column(
        "users",
        sa.Column(
            "last_name",
            sa.String(length=100),
            nullable=False,
            server_default=""
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "first_name", server_default=None)
    op.alter_column("users", "last_name", server_default=None)
    # ### end Alembic commands ###
