"""add detail to violations

Revision ID: f374fd9d5c77
Revises: 8a17949fcf30
Create Date: 2026-07-24 11:00:40.162599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f374fd9d5c77'
down_revision: Union[str, Sequence[str], None] = '8a17949fcf30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('violations', sa.Column('detail', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('violations', 'detail')
    # ### end Alembic commands ###
