"""add head-down duration tracking to exam_sessions

Revision ID: f63eba96a04c
Revises: 46a15ede953e
Create Date: 2026-07-31 09:41:11.101509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f63eba96a04c'
down_revision: Union[str, Sequence[str], None] = '46a15ede953e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_sessions', sa.Column('head_down_since', sa.DateTime(timezone=True), nullable=True))
    op.add_column('exam_sessions', sa.Column('head_down_consecutive_count', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam_sessions', 'head_down_consecutive_count')
    op.drop_column('exam_sessions', 'head_down_since')
    # ### end Alembic commands ###
